# Generated by Django 3.1.7 on 2021-04-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Koffee',
            new_name='Coffee',
        ),
        migrations.RenameField(
            model_name='coffee',
            old_name='type_chai',
            new_name='type_coffee',
        ),
    ]
