# Generated by Django 3.1.7 on 2021-04-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='chai_or_coffee',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
