# Generated by Django 3.1.7 on 2021-04-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type_chai', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
