# Generated by Django 3.1.7 on 2021-04-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_chai_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chai',
            name='photo',
            field=models.ImageField(null=True, upload_to='чай', verbose_name='tea/гринфилд.jpg'),
        ),
    ]
